# vim: set filetype=yaml.docker-compose :
services:
  www:
    build:
      context: ./www
      dockerfile: Dockerfile.dev
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - 3000:3000
    volumes:
      - ./www:/app
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - 8080:8080
    volumes:
      - ./api:/app
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - DB_HOST=postgres
      - DB_NAME=gh-repo-research
      - DB_PORT=5432
      - DB_USER=${DB_USER:-user}
      - DB_PASSWORD=${DB_PASSWORD:-password}
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:17.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: gh-repo-research
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-user} -d gh-repo-research" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
    driver: local
